Tally_Prime/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('tally_app.urls'))
]

tally1/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tapp1.urls')),
    
]

tally_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Index,name='Index'),

    path('cash_bank_books_cash_bank_summary',views.cash_bank_books_cash_bank_summary,name='cash_bank_books_cash_bank_summary'),

    path('cash_bank_books_group_summary/<int:id>',views.cash_bank_books_group_summary,name='cash_bank_books_group_summary'),

   path('cash_bank_books_ledger_monthly_summary/<int:id>',views.cash_bank_books_ledger_monthly_summary,name='cash_bank_books_ledger_monthly_summary'),

    path('cash_bank_books_ledger_show/<int:id>/<int:pk>',views.cash_bank_books_ledger_show,name='cash_bank_books_ledger_show'),

    
    #ledger

    path('account_books_ledger',views.account_books_ledger,name='account_books_ledger'),

    path('account_books_create_ledger',views.account_books_create_ledger,name='account_books_create_ledger'),

    path('create_ledger',views.create_ledger,name='create_ledger'),


    path('account_books_ledger_show2/<int:id>',views.account_books_ledger_show2,name='account_books_ledger_show2'),







    path('group_alt',views.group_alt,name='group_alt'),
    path('ledger_chequed',views.ledger_chequed,name='ledger_chequed'),
    path('ledger_chequebk',views.ledger_chequebk,name='ledger_chequebk'),
    path('ledger_bd',views.ledger_bd,name='ledger_bd'),
    path('ledger_gst',views.ledger_gst,name='ledger_gst'),
    path('ledger_taxgst ',views.ledger_taxgst ,name='ledger_taxgst'),
       

    

    

   

    
    

    

    



    
]

tally_app/models.py
from calendar import month, month_name
from contextlib import closing
from msilib.schema import Class
from xml.parsers.expat import model
from django.db import models

# Create your models here.






class Companies(models.Model):
    d_path=models.CharField(max_length=100,null=True)
    name = models.CharField(max_length=255)
    mailing_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    pincode = models.CharField(max_length=10,null=True)
    telephone = models.CharField(max_length=20,null=True)
    mobile = models.CharField(max_length=15,null=True)
    fax = models.CharField(max_length=15,null=True)
    email = models.EmailField(null=True)
    password = models.CharField(max_length=240, null=True)
    website = models.CharField(max_length=100,null=True)
    currency_symbol = models.CharField(max_length=20)
    formal_name = models.CharField(max_length=20)
    fin_begin = models.DateField()
    books_begin = models.DateField()
    fin_end = models.DateField()
    status=models.BooleanField(default=True)


class tally_group(models.Model):
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    group_name = models.CharField(max_length=255,null=True,blank=True)
    group_alias = models.CharField(max_length=255,null=True,blank=True)
    group_under = models.CharField(max_length=255,null=True,blank=True)
    nature = models.CharField(max_length=255,null=True,blank=True)
    gross_profit = models.CharField(max_length=255,null=True,blank=True)
    sub_ledger = models.CharField(max_length=255,null=True,blank=True)
    debit_credit = models.CharField(max_length=255,null=True,blank=True)
    calculation = models.CharField(max_length=255,null=True,blank=True)
    invoice = models.CharField(max_length=255,null=True,blank=True)    

class tally_ledger(models.Model):
    company=models.ForeignKey(Companies,on_delete=models.CASCADE,blank=True,null=True)
    name = models.CharField(max_length=255,blank=True,null=True)
    alias = models.CharField(max_length=255,null=True,blank=True,)
    under = models.CharField(max_length=255,blank=True,null=True)
    grp = models.ForeignKey(tally_group,on_delete = models.CASCADE,null = True,blank=True)
    mname = models.CharField(max_length=255,null=True,blank=True,)
    address = models.CharField(max_length=255,null=True,blank=True,)
    state = models.CharField(max_length=255,null=True,blank=True,)
    country = models.CharField(max_length=255,null=True,blank=True,)
    pincode = models.CharField(max_length=6,null=True,blank=True,)
    bank_details = models.CharField(max_length=20,null=True,blank=True,)
    pan_no = models.CharField(max_length=100,null=True,blank=True,)
    registration_type = models.CharField(max_length=100,null=True,blank=True)
    gst_uin = models.CharField(max_length=100,null=True,blank=True,)
    set_alter_gstdetails = models.CharField(max_length=100,null=True)
    opening_blnc = models.IntegerField(null=True,blank=True,)
    opening_blnc_type = models.CharField(max_length=100,blank=True,null=True)


    set_odl = models.CharField(max_length=255,null=True,blank=True,)
    ac_holder_nm = models.CharField(max_length=255,null=True,blank=True,)
    acc_no = models.CharField(max_length=255,null=True,blank=True,)
    ifsc_code = models.CharField(max_length=255,null=True,blank=True,)
    swift_code = models.CharField(max_length=255,null=True,blank=True,)
    bank_name = models.CharField(max_length=255,null=True,blank=True,)
    branch = models.CharField(max_length=255,null=True,blank=True,)
    SA_cheque_bk = models.CharField(max_length=20,null=True,blank=True,)
    Echeque_p = models.CharField(max_length=20,null=True,blank=True,)
    SA_chequeP_con = models.CharField(max_length=20,null=True,blank=True,)
    
    type_of_ledger = models.CharField(max_length=100,null=True,blank=True,)
    rounding_method = models.CharField(max_length=100,null=True,blank=True,)
    rounding_limit = models.IntegerField(blank=True, null=True, default=None)

    type_duty_tax = models.CharField(max_length=100,null=True,blank=True,)
    tax_type = models.CharField(max_length=100,null=True,blank=True,)
    valuation_type = models.CharField(max_length=100,null=True,blank=True,)
    rate_per_unit = models.IntegerField(blank=True, null=True, default=None,)
    percentage_of_calcution = models.CharField(max_length=100,null=True,blank=True,)
    rond_method = models.CharField(max_length=100,null=True,blank=True,)
    rond_limit = models.IntegerField(blank=True, null=True, default=None)

    gst_applicable = models.CharField(max_length=100,null=True,blank=True,)
    setalter_gstdetails = models.CharField(max_length=20,null=True,blank=True,)
    type_of_supply = models.CharField(max_length=100,null=True,blank=True,)
    assessable_value = models.CharField(max_length=100,null=True,blank=True,)
    appropriate_to = models.CharField(max_length=100,null=True,blank=True,)
    method_of_calculation = models.CharField(max_length=100,null=True,blank=True,)

    balance_billbybill = models.CharField(max_length=100,null=True,blank=True,)
    credit_period = models.CharField(max_length=100,null=True,blank=True,)
    creditdays_voucher = models.CharField(max_length=100,null=True,blank=True,)

    def __str__(self):
        return self.name




class Account_Books_Group_under(models.Model):
    group_under_Name = models.CharField(max_length=225,default="Null",blank=True)
    
    def __str__(self):
        return self.group_under_Name



class Account_Books_Ledger(models.Model):
    ledger_name = models.CharField(max_length=225,default="Null",blank=True)
    group_under =  models.ForeignKey(Account_Books_Group_under,on_delete=models.CASCADE , null=True, blank=True)
    ledger_opening_bal = models.IntegerField(default="Null",blank=True)
    ledger_opening_bal_type = models.CharField(max_length=225,default="Null",blank=True)
    
    def __str__(self):
        return self.ledger_name


class cash_bank_books_Group_Under_closing_balance(models.Model):
    
    group_under = models.ForeignKey(Account_Books_Group_under,on_delete=models.CASCADE)
    total_closing_balance_debit = models.IntegerField(default="",null=True,blank=True)
    total_closing_balance_credit = models.IntegerField(default="",null=True,blank=True)
    def __str__(self):
        return self.group_under.group_under_Name
    
    

class Months (models.Model):
    month_name=models.CharField(max_length=255)
    def __str__(self):
        return self.month_name

class cash_bank_books_Leger_Month_closing(models.Model):
    Ledger = models.ForeignKey(Account_Books_Ledger,on_delete=models.CASCADE, null=True, blank=True)  
    month = models.ForeignKey(Months,on_delete=models.CASCADE, null=True, blank=True)   
    Closing_balance = models.IntegerField(default="",null=True,blank=True)
    type = models.CharField(max_length=225)
    debit = models.IntegerField(default="",null=True,blank=True)
    credit =models.IntegerField(default="",null=True,blank=True)


         
class Account_books_Ledger_Voucher(models.Model):
    ledger = models.ForeignKey(Account_Books_Ledger, on_delete=models.CASCADE, null=True, blank=True)
    
    Date = models.DateField()
    Particualrs = models.CharField(max_length=225)
    Vch_Type = models.CharField(max_length=225)
    Vch_No = models.CharField(max_length=225)
    Debit = models.IntegerField(default="",null=True,blank=True)
    Credit = models.IntegerField(default="",null=True,blank=True)
    month = models.ForeignKey(Months,on_delete=models.CASCADE, null=True, blank=True)   

    def __str__(self):
        return self.ledger.ledger_name

class cash_bank_books_TotalClosing_balance(models.Model):
    ledger = models.ForeignKey(Account_Books_Ledger, on_delete=models.CASCADE, null=True, blank=True)
    Total_Closing_balance = models.IntegerField(default="",null=True,blank=True)
    type = models.CharField(max_length=225)

    def __str__(self):
        return self.ledger.ledger_name

tally_app/templates/account_books_ledger.html
{% extends 'base.html' %}


{% block body %}

<head>
    <script type="text/javascript">
        function searchrecords()
        {
            var input,ul,li,filter;
            input=document.getElementById("search");
            filter=input.value.toUpperCase();
            ul=document.getElementById("ulid")
            li=ul.getElementsByTagName("li")
            for(i=0;i<li.length;i++){
                let li = ul[i].getElementsByTagName('li')[0]

            }
            

        }

    </script>
    <style>
        
        thead th {
    border: .5px solid rgba(255, 255, 255, .3); ;
        }
    .ledger{

        
        background-color: rgb(65, 123, 160);
        width : 300px;
        margin: auto;
        text-align: center;
        height: 100px;
        color: #000;
        

    }
    
    .input{
        width: 80%;
       margin: auto;
       height: 30px;
       margin-top: 10px;
       color: #000;
       background-color: antiquewhite;
       border: 1px solid rgb(8, 150, 239,0.5);
       
    }
    .box{
        width : 400px;
        background-color: rgba(33,57,77,255);color:#fff;
        margin: auto;
        height: auto;

    }
    .head{
        background-color: rgb(9, 90, 203);
        
    }
    
 .create{
    height: 40px;
    text-align: end;
    color: #FFF;
    padding-right: 12px;
   padding-top: 35px;
    
 }
 hr{
    border: 1px solid rgb(12, 12, 12,.2);
 }
 .ledgers{
    color:#FFF;
    padding-left: 15px;
    width: 100%;
    text-decoration: none;
    margin-top: -15px;
    list-style:none;
 }

 tr{
    margin-left: -15px;
    cursor: pointer;
    
 }
 tr:hover{
    background-color: rgb(235, 176, 14);

 }
 tr a{
    color:#FFF;
    padding-left: 10px;

 }
 .tb{
    width: 100%;
    margin-top: -16px;
    
 }
 .selected{
    background-color: rgb(235, 176, 14);

 }
   
        
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row d-flex " style="background-color: rgb(103, 175, 220);color:#fff;color:#fff;width:100%;margin: auto;">
                    <div class="col "> Select Ledger</div>
                </div>
                
                <div class="ledger">

                    <form style="margin-top: 30px;">
                        <div class="form-group">
                            <label style="font-size: 18px; text-decoration: underline #fff; margin-top: 10px;">Name of Ledger</label>
                            <input type="text" class="input"  id="search" onkeyup="searchFun()">
                          </div>

                    </form>



                </div>

                <div class="box">
                    <div class="head px-3" style="margin-top: 5px;">List of Ledgers</div>
                    <div class="create" ><a href="{% url 'account_books_create_ledger' %}" style="color:#FFF ;">Create</a> </div>
                    <hr>

                    <table id="myTable" class="tb">
                        {% for i in ledger %}
                        <tr class="tr" style="height: 20px;">
                            
                            <td>
                                
                        <a href="{% url 'account_books_ledger_show2' i.id %}">{{i.ledger_name}}</a>
                        
                            </td>
                           
                        </tr>
                        {% endfor %}
                    </table>



                    



                </div>
                
                

              
                  


               



            </div>
        </div>
    </div>

    <script>
        const searchFun = () =>{
            let filter = document.getElementById('search').value.toUpperCase();
            let myTable = document.getElementById('myTable');
            let tr = myTable.getElementsByTagName('tr')

            for(var i=0; i<tr.length;i++){
                let td = tr[i].getElementsByTagName('td')[0];

                

                if (td){
                    let textvlue = td.textContent || td.innerHTML;
                    if (textvlue.toUpperCase().indexOf(filter) > -1){
                        tr[i].style.display = "";
                        tr[i].classList.toggle("selected")
                        

                    }else{
                        tr[i].style.display = "none";
                        
                        
                    }
                }


            }



        }

       
    </script>

      <!-- <script type="text/javascript">
        function searchFun(){
            
            input = document.getElementById("search");
            filter=input.value.toUpperCase();
            table=document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (var i=0;i<tr.length;i++)
            {
                td = tr[i].getElementsByTagName("td")[0];
                if (td)
                {
                    textdata = td.innerText;
                    if(textdata.toUpperCase().indexOf(filter)>-1)
                    {
                        
                        tr[i].style.display=""
                        tr[i].classList.toggle("selected")
                        
                        

                        
                        
                    }
                    else
                    {   
                        tr[i].style.display="None"
                        
                        
                        
                    }
                }
            
            }
            
        }
    </script> -->

{% endblock %}

tally_app/templates/cash_bank_books_cash_bank_summary.html
{% extends 'base.html' %}


{% block body %}

<head>
    
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script>
            
            

        </script>
    
    <style>

    thead th {
    border: .5px solid rgba(255, 255, 255, .3); ;
    
    
 }
 .table-row{
cursor:pointer;
}
.table-row:hover{
    background-color: rgb(216, 155, 51);
}
.table-row1{
cursor:pointer;
}
.table-row1:hover{
    background-color: rgb(216, 155, 51);
}
        
    </style>
</head>
<body>
    
 

    <div class="container-fluid">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row d-flex " style="background-color: rgb(103, 175, 220);color:#fff;width:100%;margin: auto;">
                    <div class="col "> Cash/Bank Summary</div>
                </div>
                
                <div class="table-responsive ">
                    <table  class="table  " style="background-color: rgba(33,57,77,255);color:#fff;">
                    <thead>
                        <tr>
                          <th rowspan="3" colspan="2"   class="align-middle text-white " > 
                            <h6 class="d-flex align-items-sm-start par p-1 py-1" style="margin-left: 20px;">Particular</h6>
                        </th>
                          
                          <th colspan="2" class="text-center text-white" style="width: 25%;"><h5><i>Bank Accounts</i></h5>
                            <h5>ABC PVT.LTD</h5>For 1-Apr-2022</th>
                        </tr>
                        <tr>
                          <th colspan="2" class="text-center text-white" >Closing Balance</th>
                        </tr>
                        <tr>
                            <th class="text-center text-white">Debit</th>
                            <th class="text-center text-white">Credit</th>
                          </tr>
                    </thead>

                    <tbody >

                        
                        
                        {% for i in group %}
                       
                        {% if i.account_books_ledger_set.all.exists %}
                        
                          <tr class="table-row1"  data-href="{% url 'cash_bank_books_group_summary' i.id %}">
                            {% if i.cash_bank_books_group_under_closing_balance_set.all.exists %}
                            {% for m in i.cash_bank_books_group_under_closing_balance_set.all %}
                            <td colspan="2"  >  {{ i.group_under_Name }}  </td>
                            
                            

                            
                            <td style="text-align: end;" ><strong>
                                {% if m.total_closing_balance_debit %}
                                {{m.total_closing_balance_debit }}
                                {% endif %}
                            </strong></td>
                            <td style="text-align: end;" ><strong>
                                {% if m.total_closing_balance_credit %}
                                {{m.total_closing_balance_credit }}
                                {% endif %}
                            </strong></td>
                            
                            
                            
                           {% endfor %}
                           {% else %}
                           <td colspan="2"  >  {{ i.group_under_Name }}  </td>
                            <td style="text-align: end;" ><strong></strong></td>
                            <td style="text-align: end;" ><strong></strong></td>
                           {% endif %}
                        
                        </tr>
                        {% endif %}
                        
                                
                        {% for j in i.account_books_ledger_set.all %}

                        

                        <tr class="table-row">
                            <td colspan="2"><span style="margin-left: 20px;">{{j.ledger_name}} </span></td>
                            {% if j.cash_bank_books_totalclosing_balance_set.all.exists %}
                            {% for l in j.cash_bank_books_totalclosing_balance_set.all %}
                            
                            {% if l.type == "Dr" %}
                            <td style="text-align: end;"><strong>
                                {% if l.Total_Closing_balance  %}
                                {{l.Total_Closing_balance }}
                                {% endif %}
                            </strong></td>
                            <td style="text-align: end;"><strong></strong></td>
                            {% else %}
                            <td style="text-align: end;"><strong></strong></td>
                            <td style="text-align: end;"><strong>
                                {% if l.Total_Closing_balance  %}
                                {{l.Total_Closing_balance }}
                                {% endif %}
                            </strong></td>
                            {% endif %}


                            {% endfor %}
                            {% else %}
                            <td style="text-align: end;"></td>
                            <td></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                           
                        
                        {% endfor %}
                        
                    
                    
                    
                        <tr class="table-row">
                            <th colspan="2" ><h6 class="d-flex align-items-sm-start par p-1 py-1 foot" style="margin-left: 20px;">Grand Total</h6></th>
                            
                            
                            <th   style="text-align: end;">{{total_debit}}</th>
                            <th  style="text-align: end;">{{total_credit}}</th>
                            
                        </tr>

                    </tbody>




                    </table>


                  </div>

              
                  


               



            </div>
        </div>
    </div>

<script>
    $(document).ready(function($) {
        $(".table-row1").click(function() {
            window.document.location = $(this).data("href");
        });
    });
</script>
{% endblock %}

tally_app/templates/cash_bank_books_cash_bank_summary2.html
{% extends 'base.html' %}


{% block body %}

<head>
    <style>

thead th {
    border: .5px solid rgba(255, 255, 255, .3); ;
    
    
 }
 .table-row{
cursor:pointer;
}
.table-row:hover{
    background-color: rgb(216, 155, 51);
}
.table-row1{
cursor:pointer;
}
.table-row1:hover{
    background-color: rgb(216, 155, 51);
}    
        
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row d-flex " style="background-color: rgb(103, 175, 220);color:#fff;width:100%;margin: auto;">
                    <div class="col "> Group Summary</div>
                </div>
                
                <div class="table-responsive">
                    <table  class="table   " style="background-color: rgba(33,57,77,255);color:#fff;">
                        <thead>
                        <tr>
                          <th rowspan="3" colspan="2"   class="align-middle text-white "> <h6 class="d-flex align-items-sm-start par p-1 py-1" style="margin-left: 20px;">Particular</h6></th>
                          
                          <th colspan="2" class="text-center text-white" style="width: 25%;"><h5><i>Bank Accounts</i></h5>
                            <h5>ABC PVT.LTD</h5>For 1-Apr-2022</th>
                        </tr>
                        <tr>
                          <th colspan="2" class="text-center text-white">Closing Balance</th>
                        </tr>
                        <tr>
                          <th class="text-center text-white">Debit</th>
                          <th class="text-center text-white">Credit</th>
                        </tr>
                    </thead>

                    <tbody >
                        
                        {% for i in ledger %}
                        
                    
                        <tr class="table-row"  data-href="{% url 'cash_bank_books_ledger_monthly_summary' i.id %}">
                            <td colspan="2">{{i.ledger_name}}</td>
                            {% if i.cash_bank_books_totalclosing_balance_set.all.exists %}
                            {% for j in i.cash_bank_books_totalclosing_balance_set.all %}
                            {% if j.type == "Dr" %}
                            <td style="text-align: end;"><strong>
                                {% if j.Total_Closing_balance %}
                                {{j.Total_Closing_balance}}
                                {% endif %}
                            </strong></td>
                            <td><strong></strong></td>
                            {% else %}
                            <td style="text-align: end;"><strong></strong></td>
                            <td style="text-align: end;"><strong>
                                {% if j.Total_Closing_balance %}
                                {{j.Total_Closing_balance}}
                                {% endif %}
                            </strong></td>
                            {% endif %}
                            
                            {% endfor %}
                            {% else %}
                            <td style="text-align: end;"></td>
                            <td></td>
                            {% endif %}
                            

                        </tr>
                        
                        {% endfor %}
                        <!-- <tr>
                            <td colspan="2">HDFC</td>
                            <td style="text-align: end;">2,672.00</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td colspan="2">Icici Bank</td>
                            <td style="text-align: end;">1,000.00</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td colspan="2">SBI</td>
                            <td></td>
                            <td style="text-align: end;">22,000.00</td>
                        </tr> -->

                        <tr>
                            <th colspan="2" ><h6 class="d-flex align-items-sm-start par p-1 py-1 foot" style="margin-left: 20px;">Grand Total</h6></th>
                            
                            <th   style="text-align: end;">{{total_debit}}</th>
                            <th  style="text-align: end;">{{total_credit}}</th>
                            
                        </tr>

                    </tbody>




                    </table>


                  </div>

              
                  


               



            </div>
        </div>
    </div>

    <script>
        $(document).ready(function($) {
            $(".table-row").click(function() {
                window.document.location = $(this).data("href");
            });
        });
    </script>

{% endblock %}

tally_app/templates/index.html
{% extends 'base.html' %}


{% block body %}





{% endblock %}